### ISSUE TITLE
ipv6环境访问出错

### ISSUE THREAD

**Issue by liwuking** [jack2gs/IPv6Synthesization#1]
楼主，你好，我问下，我app里面用的是NSURLSession，暂时使用ipv4地址，没有域名，我用你这个类把ipv4转成ipv6后，然后用NSURLSession访问，发现ipv6环境下访问不了，是IOS8的环境测试的，ios9以上系统NSURLSession自动吧ipv4转成ipv6了。问下楼主，我是哪里用错了还是怎么的

**Comment by jack2gs** [comment]
@liwuking 你好，在iOS8下合成的IPv6地址正确么？另外，你的URL形式是否正确：http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html。IPv4和IPv6的URL是不一样的。

**Comment by liwuking** [comment]
不敢保证不转错，比如我本来的地址是http://120.76.136.69/cn。然后我把你这个项目中main函数的第一行代码改成uint8_t ipv4[4] = {120, 76, 136, 69}; 我的imac电脑连接我的macpro的NAT64环境，输出数据有两个host=2001:2:0:1baa::c000:ab, serv=0
host=2001:2:0:1baa::c000:aa, serv=0.   这样我猜是错了吧，错在哪里，楼主

**Comment by jack2gs** [comment]
转换后的地址你可以自己ping下，试试通不通。这个函数会返回好几个合成的地址，可以先测试连通性，然后再选取一个可用的去构造URL。还有你的IPv6形式的URL是？我这边用的就是我写的这个函数，已经通过苹果审核了。
